# Generated by Django 2.0.1 on 2018-01-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=400)),
                ('pub_name', models.CharField(default='', max_length=255)),
                ('volume', models.CharField(max_length=255, null=True)),
                ('pages', models.CharField(blank=True, default='', max_length=255)),
                ('doi', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.CharField(default='', max_length=255)),
                ('pub_year', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-pub_year'],
            },
        ),
    ]
