# Generated by Django 2.0.1 on 2018-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20180118_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
