# Generated by Django 2.0.1 on 2018-01-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('joined_group', models.IntegerField(default=0)),
                ('left_group', models.IntegerField(blank=True, default=0)),
                ('currently', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(choices=[('Undergraduate Researcher', 'Undergraduate Researcher'), ('Graduate Student', 'Graduate Student'), ('Post-Doctoral Researcher', 'Post-Doctoral Researcher'), ('Visiting Scholar', 'Visiting Scholar')], default='Undergraduate Researcher', max_length=255)),
            ],
            options={
                'ordering': ['-order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('joined_group', models.IntegerField(default=0)),
                ('left_group', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('background_link', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-order'],
                'abstract': False,
            },
        ),
    ]
