# Generated by Django 2.0.1 on 2018-01-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='labmember',
            name='group',
            field=models.CharField(choices=[('Undergraduate Researcher', 'Undergraduate Researcher'), ('Graduate Student', 'Graduate Student'), ('Visiting Scholar/Post-Doctoral Researcher', 'Visiting Scholar/Post-Doctoral Researcher')], default='Undergraduate Researcher', max_length=255),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='position',
            field=models.CharField(default='Undergraduate Researcher', max_length=255),
        ),
    ]
