# Generated by Django 2.0.1 on 2018-01-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180119_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labmember',
            old_name='position',
            new_name='title',
        ),
    ]
