# Generated by Django 2.0.1 on 2018-01-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180119_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labmember',
            old_name='joined_group',
            new_name='joined_group_year',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='joined_group',
            new_name='joined_group_year',
        ),
    ]
