# Generated by Django 2.0.1 on 2018-01-20 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20180119_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labmember',
            name='joined_group_year',
        ),
        migrations.RemoveField(
            model_name='labmember',
            name='left_group_year',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='joined_group_year',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='left_group_year',
        ),
        migrations.AddField(
            model_name='labmember',
            name='joined_group',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='labmember',
            name='left_group',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='staff',
            name='joined_group',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='staff',
            name='left_group',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
