# Generated by Django 2.0.1 on 2018-01-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20180119_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
