# Generated by Django 2.0.1 on 2018-01-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=255)),
                ('semester_year', models.DateField()),
                ('semester_season', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('course_dept_num', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
