# Generated by Django 2.0.1 on 2018-01-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_auto_20180114_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-semester_year']},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_dept_num',
            field=models.CharField(default='', max_length=255, verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school_year',
            field=models.CharField(max_length=255, verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester_season',
            field=models.CharField(max_length=255, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester_year',
            field=models.IntegerField(default='', verbose_name='Year'),
        ),
    ]
