# Generated by Django 2.0.1 on 2018-01-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20180114_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester_year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
