# Generated by Django 2.0.1 on 2018-01-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0006_course_course_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_state',
            field=models.CharField(choices=[(1, 'Previous Year'), (2, 'Current Year'), (3, 'Next Year')], default='1', max_length=255),
        ),
    ]
