# Generated by Django 2.0.1 on 2018-01-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0008_auto_20180114_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_state',
            field=models.CharField(choices=[('Previous Year', 'Previous Year'), ('Current Year', 'Current Year'), ('Next Year', 'Next Year')], default='Current Year', max_length=255),
        ),
    ]
