# Generated by Django 2.0.1 on 2018-01-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0009_auto_20180114_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'ordering': ['course_dept_num']},
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course_dept_num',
            field=models.CharField(default='', max_length=255, verbose_name='Course Number'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course_title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='full_description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_state',
            field=models.CharField(choices=[('Previous Year', 'Previous Year'), ('Current Year', 'Current Year'), ('Next Year', 'Next Year')], default='Previous Year', max_length=255),
        ),
    ]
