# Generated by Django 2.0.1 on 2018-01-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0010_auto_20180118_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDetail',
            new_name='CoursePage',
        ),
    ]
