# Generated by Django 2.0.1 on 2018-01-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0012_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
