# Generated by Django 2.0.1 on 2018-01-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0014_auto_20180118_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
