# Generated by Django 2.0.1 on 2018-01-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0016_auto_20180118_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
