# Generated by Django 2.0.1 on 2018-01-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0017_delete_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
